[tools]
sops = "latest"
"go:github.com/yieldray/surgecli" = "latest"
go = "latest"


[env]
_ = { file = "{ path = .env, tools = true }" }
SOPS_AGE_RECIPIENTS = "age1a9p2k3u40mvdntpad4ga7akvnnqqwm6eskfr2yxkgq3u9lp7jfns2wgqty, age155th0ptdjf3gkp7pmzqcepe9kec9n3w32l87czf29fda4a2gj49ql0pg8a"

[tasks]
encrypt = "sops -e -i .env && mv .env .env.example"
decrypt = "mv .env.example .env && sops -d -i .env"
docs = "mise run makko && ./makko* docs && cp docs/index.html docs/web/index.html && cp docs/script.js docs/web/script.js && cp docs/robots.txt docs/web/robots.txt"
makko = "go run ./bin/makko.go"
deploy = "mise run docs && surgecli deploy ./docs/web newsy.surge.sh"
wasm = "GOOS=js GOARCH=wasm go build -o newsy.wasm"

[deps]
go = { auto = true }

[settings]
experimental = true
